### PR TITLE
Add OS X 64 bit support

### LINKED ISSUE #3: Add support for OS X 64 bit build
Now that OS X has dropped support for x86 entirely, the darwin build needs updated.

### PR DESCRIPTION
**Pull request by ameliabradley**
Closes #3

### CODE REVIEW

**Comment by ameliabradley** [comment]
Install XQuartz by visiting https://www.xquartz.org and installing the latest
(currently 2.7.11) from there. This will create the necessary /usr/X11R6 directories

**Comment by ameliabradley** [comment]
Oh yeah... this doesn't do anything for the OS X arm build. Just 64 bit. I don't have a machine to test arm + Darwin on.

**Comment by ameliabradley** [comment]
@lvella Is there anything else this PR needs?

**Comment by lvella** [comment]
Why did you remove Windows name check? I don't know if that is bad or good, but we have 2 ways to go with this repo: either we actively develop it to bring the game to a modern age, or we just do the bare minimum to keep it working. I don't have time to do the first, so I think the removal of the windows check is out of place, for philological reasons.

**Comment by lvella** [comment]
I have partially merged up to the Windows check removal...

**Comment by ameliabradley** [comment]
@lvella I added the uname_S variable so the build would automatically use the correct configuration if the target was detected as x86_64, with this commit: https://github.com/lvella/xevil/pull/4/commits/1680e282307fbf5c2a1fd94c4b1ebe8eee521805

You removed the only reference to uname_S with your commit here:
https://github.com/lvella/xevil/pull/4/commits/3b9079930150cd89669672e679dd55b93b556212

Meaning that now uname_S was just an unused variable, which is why I removed it.

If you'd like to use it for something, that makes sense. I think we could potentially use it to automatically detect and build the correct architecture by default. Right now it does not appear to be used for anything though?

**Comment by lvella** [comment]
Oh, sorry, I didn't notice that variable was your's.

**Pull request merged**
